# Attention!
# Length unit is in centimeter.
# Angle unit is in degree.
# Left-handed coordinate system.
# Just as UE5.

[VCCSimPresets]

IP = "0.0.0.0"
Port = 50996

# Name or Tag, but tag is recommended.
# If there is only one robot, the tag is not necessary.
MainCharacter = "Flash"
StaticMeshActor = ["MFMesh", "CompanionCube"]   # Name or Tag
ManualControl = true

SubWindows = ["Lit", "Unit", "PointCloud"]
SubWindowsOpacities = [0.95, 0.85, 0.75]
StartWithRecording = false
UseMeshManager = true
MeshMaterial = "/VCCSim/Materials/M_Static_mesh"
LS_StartOffset = 0                              # Frame
BufferSize = 100
LogSavePath = "C:/UEProjects/VCCSimDev/Plugins/VCCSim/Logs"
DefaultDronePawn = "/VCCSim/Pawn/Drone/BP_PreciseDrone_1C_1D_L.BP_PreciseDrone_1C_1D_L_C"
DefaultCarPawn = "/VCCSim/Pawn/Husky/Blueprints/BP_CarPawn_Husky.BP_CarPawn_Husky_C"
DefaultFlashPawn = "/VCCSim/Pawn/Flash/BP_FlashPawn.BP_FlashPawn_C"

[[Robots]]

UETag = "Mavic"
Type = "Drone"
RecordInterval = -0.5

#[Robots.ComponentConfigs.Lidar]
#RecordInterval = -0.5
#NumRays = 32
#NumPoints = 16000
#ScannerRangeInner = 300
#ScannerRangeOuter = 3000
#ScannerAngleUp = 25
#ScannerAngleDown = 25
#bVisualizePoints = false

[Robots.ComponentConfigs.RGBCamera]
RecordInterval = -0.033333
FOV = 90
Width = 1280
Height = 720
bOrthographic = false

#[Robots.ComponentConfigs.DepthCamera]
#RecordInterval = -0.033333
#FOV = 90
#Width = 1280
#Height = 720
#MaxRange = 3000.0
#MinRange = 0.0
#bOrthographic = false

[Robots.ComponentConfigs.SegmentationCamera]
RecordInterval = -0.033333
FOV = 90
Width = 1280
Height = 720

#[[Robots]]
#
#UETag = "Husky"
#Type = "Car"
#
#[Robots.ComponentConfigs.Lidar]
#NumRays = 32
#NumPoints = 16000
#ScannerRangeInner = 100
#ScannerRangeOuter = 4000
#ScannerAngleUp = 35
#ScannerAngleDown = 25
#bVisualizePoints = true

#[[Robots]]
#
#UETag = "Flash"
#Type = "Flash"
#RecordInterval = -1
#
#[Robots.ComponentConfigs.RGBCamera]
#RecordInterval = -1
#FOV = 90
#Width = 1920
#Height = 1080
#bOrthographic = false